version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/app
      - ./docker/nginx/default.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - default
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/app
    environment:
      PHP_IDE_CONFIG: 'serverName=docker'
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=folderpro
      - MYSQL_USER=fprouser
      - MYSQL_PASSWORD=fprouser
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST:%
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker/mysql/database:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

networks:
  default:
    driver: bridge